/**
 * Guesses whether a string is HTML (generated by Tiptap) or plain text (older articles).
 *
 * KB articles created before the switch to rich text are still plain text with
 * `\n` line breaks. We can't force everything through a single render path: HTML
 * rendered as text would leak tags, and text rendered as HTML would lose its line
 * breaks. This function lets us keep both.
 *
 * Only recognizes the block tags Tiptap actually emits at the start of a string —
 * to avoid mistaking plain text containing a `<` character (e.g. "temperature < 5°C").
 */
const HTML_START = /^\s*<(p|h[1-6]|ul|ol|blockquote|pre|img|div|hr)[\s>/]/i;

export function isHtmlContent(value?: string | null): boolean {
  if (!value) return false;
  return HTML_START.test(value);
}
