import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { formatDateTime } from "@/shared/utils/datetime";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  ArrowLeft,
  Pencil,
  Upload,
  Archive,
  Trash2,
  History,
} from "lucide-react";
import { ErrorState } from "@/shared/components/ui/ErrorState";
import { RichContentView } from "@/shared/components/editor/RichContentView";
import { BlogStatusBadge, BlogOriginBadge } from "./BlogStatusBadge";
import { BlogVersionHistory } from "./BlogVersionHistory";
import { BlogDiffViewer } from "./BlogDiffViewer";
import {
  useBlogDetail,
  useBlogGenerationStatus,
  useBlogVersions,
  useBlogCompare,
  usePublishBlogPost,
  useArchiveBlogPost,
  useDeleteBlogPost,
  isBlogEditable,
} from "@/shared/hooks/blog/useBlog";
import { BlogPostStatusEnum } from "@/shared/enums/blog/blog.enum";
import type { BlogCompareParams } from "@/shared/types/blog/blog.types";
import { ACTIONS } from "@/shared/constants/actions";

interface BlogDetailViewProps {
  basePath: string;
  /** Only Manager/Admin have publish, archive and delete. */
  canWorkflow?: boolean;
}

/**
 * One blog post, read the way a reader would meet it.
 *
 * The post is the page, so it gets a single reading column and the summary sits above the
 * body as a lede rather than being boxed with it. Identity and actions stay pinned to the
 * top, which keeps Publish reachable from the bottom of a long post.
 */
export function BlogDetailView({ basePath, canWorkflow }: BlogDetailViewProps) {
  const { id = "" } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [showVersions, setShowVersions] = useState(false);
  const [compareParams, setCompareParams] = useState<BlogCompareParams | null>(
    null,
  );
  const [confirmDelete, setConfirmDelete] = useState(false);

  const { data: post, isLoading, isError, refetch } = useBlogDetail(id);

  // Post is being generated by AI → poll until Draft / GenerationFailed
  const isGenerating = post?.status === BlogPostStatusEnum.Generating;
  useBlogGenerationStatus(id, isGenerating);

  const { data: versions } = useBlogVersions(showVersions ? id : "");
  const { data: diff } = useBlogCompare(id, compareParams);

  const { mutate: publish, isPending: publishing } = usePublishBlogPost();
  const { mutate: archive, isPending: archiving } = useArchiveBlogPost();
  const { mutate: remove, isPending: removing } = useDeleteBlogPost();

  if (isError)
    return (
      <div className="p-6">
        <ErrorState
          message="Post not found or you don't have permission to view it."
          onRetry={refetch}
        />
      </div>
    );

  if (isLoading || !post)
    return (
      <div>
        <div className="border-b border-border">
          <div className="flex h-14 w-full items-center gap-3 pl-(--page-pl) pr-(--page-pr)">
            <Skeleton className="h-7 w-20" />
            <Skeleton className="h-4 w-24" />
            <Skeleton className="ml-auto h-7 w-56" />
          </div>
        </div>
        <div className="w-full space-y-4 pt-10 pl-(--page-pl) pr-(--page-pr)">
          <Skeleton className="h-9 w-4/5" />
          <Skeleton className="h-3 w-64" />
          <div className="space-y-2.5 pt-6">
            {Array.from({ length: 10 }).map((_, i) => (
              <Skeleton key={i} className="h-3.5 w-full last:w-2/3" />
            ))}
          </div>
        </div>
      </div>
    );

  const editable = isBlogEditable(post.status);
  const canPublish = post.status === BlogPostStatusEnum.Draft;

  return (
    <div className="pb-24">
      {/* The toolbar spans the page, not the reading column: the post wants a narrow
          measure, the action row wants room to stay on one line. */}
      <div className="sticky top-0 z-20 border-b border-border bg-background/85 backdrop-blur supports-[backdrop-filter]:bg-background/70">
        <div className="flex w-full flex-wrap items-center gap-x-3 gap-y-2 py-2.5 pl-(--page-pl) pr-(--page-pr)">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate(`${basePath}/blog`)}
          >
            <ArrowLeft className="size-3.5" />
            Blog
          </Button>
          <BlogStatusBadge status={post.status} />
          <BlogOriginBadge origin={post.origin} />

          <div className="ml-auto flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              className="gap-1.5"
              onClick={() => setShowVersions(true)}
            >
              <History className="size-3.5" /> History
            </Button>

            {canWorkflow && (
              <>
                <Tooltip>
                  <TooltipTrigger
                    render={
                      <Button
                        variant="outline"
                        size="sm"
                        className="gap-1.5"
                        disabled={!canPublish || publishing}
                        onClick={() => publish(post.id)}
                      />
                    }
                  >
                    <Upload className="size-3.5" /> Publish
                  </TooltipTrigger>
                  {!canPublish && (
                    <TooltipContent>
                      Only draft posts can be published
                    </TooltipContent>
                  )}
                </Tooltip>
                <Button
                  variant="outline"
                  size="sm"
                  className="gap-1.5"
                  disabled={
                    archiving || post.status === BlogPostStatusEnum.Archived
                  }
                  onClick={() => archive(post.id)}
                >
                  <Archive className="size-3.5" /> Archive
                </Button>
                {/* destructive, not outline: delete is the one irreversible action in this
                    row, so it must not look like Publish or Archive sitting beside it. */}
                <Button
                  variant="destructive"
                  size="sm"
                  className="gap-1.5"
                  disabled={removing}
                  onClick={() => setConfirmDelete(true)}
                >
                  <Trash2 className="size-3.5" /> {ACTIONS.DELETE}
                </Button>
              </>
            )}

            <span aria-hidden className="mx-1 h-5 w-px bg-border" />
            <Button
              size="sm"
              className="gap-1.5"
              disabled={!editable}
              title={
                editable
                  ? undefined
                  : "Post is being generated or already archived"
              }
              onClick={() => navigate(`${basePath}/blog/${post.id}/edit`)}
            >
              <Pencil className="size-3.5" /> {ACTIONS.EDIT}
            </Button>
          </div>
        </div>
      </div>

      {/* Two columns, matching the editor and the guide page: the post body on the
          left, its title and facts in a card on the right. */}
      <div className="grid w-full items-start gap-8 pt-8 pl-(--page-pl) pr-(--page-pr) lg:grid-cols-[minmax(0,1fr)_340px]">
        {/* The body sits on the same card surface as the panel beside it: bare text on
            the page background against a bordered card read as an unfinished column. */}
        <article className="min-w-0 rounded-lg border border-border bg-card p-6">
          {post.status === BlogPostStatusEnum.Generating && (
            <p className="mb-5 rounded-md border border-info/40 bg-info/5 px-3 py-2.5 text-sm">
              AI is writing this post. The page updates itself when it finishes.
            </p>
          )}

          {post.status === BlogPostStatusEnum.GenerationFailed && (
            <p className="mb-5 rounded-md border border-destructive/40 bg-destructive/5 px-3 py-2.5 text-sm">
              AI generation failed. Open the editor to write the post by hand.
            </p>
          )}

          <div className="text-sm">
            <RichContentView html={post.contentHtml} />
          </div>
        </article>

        <aside className="space-y-5 rounded-lg border border-border bg-card p-5 lg:sticky lg:top-20">
          <h1 className="text-xl font-semibold leading-tight tracking-tight">
            {post.title}
          </h1>

          {/* Slug omitted: it is a URL detail the editor sets, not something a reader of
              this page acts on. */}
          <dl className="space-y-2.5 border-t border-border pt-4 text-xs">
            <div className="flex items-baseline justify-between gap-3">
              <dt className="text-muted-foreground">Version</dt>
              <dd className="font-medium tabular-nums">
                {post.currentVersion}
              </dd>
            </div>
            <div className="flex items-baseline justify-between gap-3">
              <dt className="text-muted-foreground">Written</dt>
              <dd className="font-medium tabular-nums">
                {formatDateTime(post.createdAt)}
              </dd>
            </div>
          </dl>

          <div className="border-t border-border pt-4">
            <p className="text-xs text-muted-foreground">Summary</p>
            <p className="mt-2 text-sm leading-relaxed text-foreground/80">
              {post.summary}
            </p>
          </div>
        </aside>
      </div>

      <Dialog open={showVersions} onOpenChange={setShowVersions}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle>Version history</DialogTitle>
          </DialogHeader>
          <BlogVersionHistory
            versions={versions ?? []}
            onCompare={(oldVersionNumber, newVersionNumber) =>
              setCompareParams({ oldVersionNumber, newVersionNumber })
            }
          />
          {diff && (
            <div className="mt-3 border-t pt-3">
              <BlogDiffViewer diff={diff} />
            </div>
          )}
        </DialogContent>
      </Dialog>

      <AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete this post?</AlertDialogTitle>
            <AlertDialogDescription>
              <strong>{post.title}</strong> will be deleted. This cannot be
              undone from the UI.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{ACTIONS.CANCEL}</AlertDialogCancel>
            <AlertDialogAction
              variant="destructive"
              onClick={() =>
                remove(post.id, {
                  onSuccess: () => navigate(`${basePath}/blog`),
                })
              }
            >
              {ACTIONS.DELETE}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
