import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  ArrowLeft,
  Pencil,
  Upload,
  Archive,
  Trash2,
  History,
} from "lucide-react";
import { ErrorState } from "@/shared/components/ui/ErrorState";
import { RichContentView } from "@/shared/components/editor/RichContentView";
import { BlogStatusBadge, BlogOriginBadge } from "./BlogStatusBadge";
import { BlogVersionHistory } from "./BlogVersionHistory";
import { BlogDiffViewer } from "./BlogDiffViewer";
import {
  useBlogDetail,
  useBlogGenerationStatus,
  useBlogVersions,
  useBlogCompare,
  usePublishBlogPost,
  useArchiveBlogPost,
  useDeleteBlogPost,
  isBlogEditable,
} from "@/shared/hooks/blog/useBlog";
import { BlogPostStatusEnum } from "@/shared/enums/blog/blog.enum";
import type { BlogCompareParams } from "@/shared/types/blog/blog.types";

interface BlogDetailViewProps {
  basePath: string;
  /** Only Manager/Admin have publish · archive · delete. */
  canWorkflow?: boolean;
}

export function BlogDetailView({ basePath, canWorkflow }: BlogDetailViewProps) {
  const { id = "" } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [showVersions, setShowVersions] = useState(false);
  const [compareParams, setCompareParams] = useState<BlogCompareParams | null>(
    null,
  );
  const [confirmDelete, setConfirmDelete] = useState(false);

  const { data: post, isLoading, isError, refetch } = useBlogDetail(id);

  // Post is being generated by AI → poll until Draft / GenerationFailed
  const isGenerating = post?.status === BlogPostStatusEnum.Generating;
  useBlogGenerationStatus(id, isGenerating);

  const { data: versions } = useBlogVersions(showVersions ? id : "");
  const { data: diff } = useBlogCompare(id, compareParams);

  const { mutate: publish, isPending: publishing } = usePublishBlogPost();
  const { mutate: archive, isPending: archiving } = useArchiveBlogPost();
  const { mutate: remove, isPending: removing } = useDeleteBlogPost();

  if (isError)
    return (
      <div className="p-6">
        <ErrorState
          message="Post not found or you don't have permission to view it."
          onRetry={refetch}
        />
      </div>
    );

  if (isLoading || !post)
    return (
      <div className="mx-auto max-w-4xl space-y-4 p-6">
        <Skeleton className="h-8 w-2/3" />
        <Skeleton className="h-64 w-full" />
      </div>
    );

  const editable = isBlogEditable(post.status);
  const canPublish = post.status === BlogPostStatusEnum.Draft;

  return (
    <div className="mx-auto max-w-4xl space-y-5 p-6">
      <Button
        variant="ghost"
        size="sm"
        onClick={() => navigate(`${basePath}/blog`)}
      >
        <ArrowLeft className="size-3.5" /> Blog list
      </Button>

      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="min-w-0">
          <h1 className="text-2xl font-semibold tracking-tight">
            {post.title}
          </h1>
          {/* Slug omitted: it is a URL detail the editor sets, not something a reader of
              this page acts on — the title above already identifies the post. */}
          <p className="text-muted-foreground mt-1 font-mono text-xs">
            v{post.currentVersion} &middot;{" "}
            {format(new Date(post.createdAt), "MM/dd/yyyy HH:mm")}
          </p>
          <div className="mt-2 flex flex-wrap items-center gap-1.5">
            <BlogStatusBadge status={post.status} />
            <BlogOriginBadge origin={post.origin} />
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setShowVersions(true)}
          >
            <History className="size-3.5" /> History
          </Button>
          <Button
            size="sm"
            disabled={!editable}
            title={
              editable
                ? undefined
                : "Post is being generated or already archived"
            }
            onClick={() => navigate(`${basePath}/blog/${post.id}/edit`)}
          >
            <Pencil className="size-3.5" /> Edit
          </Button>

          {canWorkflow && (
            <>
              <Button
                variant="outline"
                size="sm"
                disabled={!canPublish || publishing}
                onClick={() => publish(post.id)}
              >
                <Upload className="size-3.5" /> Publish
              </Button>
              <Button
                variant="outline"
                size="sm"
                disabled={
                  archiving || post.status === BlogPostStatusEnum.Archived
                }
                onClick={() => archive(post.id)}
              >
                <Archive className="size-3.5" /> Archive
              </Button>
              {/* destructive, not outline: delete is the one irreversible action in this
                  row, so it must not look like Publish or Archive sitting beside it.
                  Matches the Delete button on the guide-article detail page. */}
              <Button
                variant="destructive"
                size="sm"
                disabled={removing}
                onClick={() => setConfirmDelete(true)}
              >
                <Trash2 className="size-3.5" /> Delete
              </Button>
            </>
          )}
        </div>
      </div>

      {post.status === BlogPostStatusEnum.Generating && (
        <Card className="border-info/40 bg-info/5 p-3 text-sm">
          AI is generating content. The page will update automatically when
          done.
        </Card>
      )}

      {post.status === BlogPostStatusEnum.GenerationFailed && (
        <Card className="border-destructive/40 bg-destructive/5 p-3 text-sm">
          AI content generation failed. You can still click{" "}
          <strong>Edit</strong> to write it manually.
        </Card>
      )}

      <Card className="p-5">
        <p className="text-muted-foreground mb-3 text-sm italic">
          {post.summary}
        </p>
        <RichContentView html={post.contentHtml} />
      </Card>

      <Dialog open={showVersions} onOpenChange={setShowVersions}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle>Version history</DialogTitle>
          </DialogHeader>
          <BlogVersionHistory
            versions={versions ?? []}
            onCompare={(oldVersionNumber, newVersionNumber) =>
              setCompareParams({ oldVersionNumber, newVersionNumber })
            }
          />
          {diff && (
            <div className="mt-3 border-t pt-3">
              <BlogDiffViewer diff={diff} />
            </div>
          )}
        </DialogContent>
      </Dialog>

      <AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete post?</AlertDialogTitle>
            <AlertDialogDescription>
              The post &ldquo;{post.title}&rdquo; will be deleted. This cannot
              be undone from the UI.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              variant="destructive"
              onClick={() =>
                remove(post.id, {
                  onSuccess: () => navigate(`${basePath}/blog`),
                })
              }
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
