import { useEffect, useRef } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { blogService } from "@/shared/services/blog/blog.service";
import { QUERY_KEY, KEY } from "@/shared/utils/queryKeys";
import { handleErrorApi } from "@/shared/lib/errors";
import { checkRole } from "@/shared/lib/authz";
import { useSessionStore } from "@/shared/stores/sessionStore";
import { UserRole } from "@/shared/types/account/session.types";
import {
  BlogPostStatusEnum,
  BLOG_GENERATION_TERMINAL_STATUSES,
} from "@/shared/enums/blog/blog.enum";
import type {
  BlogPostListParams,
  BlogTemplateListParams,
  BlogCompareParams,
  CreateBlogPostPayload,
  UpdateBlogPostPayload,
} from "@/shared/types/blog/blog.types";

/** Max poll count while waiting for AI generation (~2 minutes at a 3s interval). */
const GENERATION_POLL_LIMIT = 40;
const GENERATION_POLL_INTERVAL = 3000;

// ── Read: public (Published posts only) ──

export function useBlogPublicList(params?: BlogPostListParams) {
  return useQuery({
    queryKey: QUERY_KEY.blog.publicList(params),
    queryFn: () => blogService.getPublicList(params).then((r) => r.data.data),
  });
}

export function useBlogPublicDetail(id: string) {
  return useQuery({
    queryKey: QUERY_KEY.blog.publicDetail(id),
    queryFn: () => blogService.getPublicDetail(id).then((r) => r.data.data),
    enabled: !!id,
  });
}

// ── Read: internal (all statuses) ──

export function useBlogList(params?: BlogPostListParams) {
  return useQuery({
    queryKey: QUERY_KEY.blog.list(params),
    queryFn: () => blogService.getList(params).then((r) => r.data.data),
  });
}

export function useBlogDetail(id: string) {
  return useQuery({
    queryKey: QUERY_KEY.blog.detail(id),
    queryFn: () => blogService.getDetail(id).then((r) => r.data.data),
    enabled: !!id,
  });
}

/**
 * Poll a post being generated by AI until it reaches a terminal status
 * (`Draft` = done, `GenerationFailed` = error), or exceeds `GENERATION_POLL_LIMIT` polls.
 *
 * Uses the internal endpoint — the public detail endpoint returns 404 while the post isn't Published.
 */
export function useBlogGenerationStatus(id: string, enabled: boolean) {
  // Counted locally, NOT via query.state.dataUpdateCount: this hook shares its
  // queryKey with useBlogDetail, so dataUpdateCount would also count fetches from
  // the detail page → polling could stop earlier than the limit (even on the first poll).
  const pollCount = useRef(0);

  useEffect(() => {
    if (enabled) pollCount.current = 0;
  }, [enabled, id]);

  return useQuery({
    queryKey: QUERY_KEY.blog.detail(id),
    queryFn: () => blogService.getDetail(id).then((r) => r.data.data),
    enabled: enabled && !!id,
    staleTime: 0,
    refetchInterval: (query) => {
      const status = query.state.data?.status;
      // Stop once done/failed
      if (status && BLOG_GENERATION_TERMINAL_STATUSES.includes(status))
        return false;
      // Stop once the wait limit is exceeded — avoids polling forever if the worker hangs
      if (pollCount.current >= GENERATION_POLL_LIMIT) return false;
      pollCount.current += 1;
      return GENERATION_POLL_INTERVAL;
    },
  });
}

export function useBlogVersions(id: string) {
  return useQuery({
    queryKey: QUERY_KEY.blog.versions(id),
    queryFn: () => blogService.getVersions(id).then((r) => r.data.data),
    enabled: !!id,
  });
}

export function useBlogCompare(id: string, params: BlogCompareParams | null) {
  return useQuery({
    queryKey: QUERY_KEY.blog.compare(
      id,
      params?.oldVersionNumber,
      params?.newVersionNumber,
    ),
    queryFn: () => blogService.compare(id, params!).then((r) => r.data.data),
    enabled: !!id && !!params,
  });
}

// ── Read: blog templates (Staff+) ──

export function useBlogTemplates(params?: BlogTemplateListParams) {
  return useQuery({
    queryKey: QUERY_KEY.blogTemplates.list(params),
    queryFn: () => blogService.getTemplates(params).then((r) => r.data.data),
  });
}

// ── Write: authoring (Staff+) ──
// Forms use mutateAsync + try/catch + handleErrorApi({ error, setError }) in the component.

export function useCreateBlogPost() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (payload: CreateBlogPostPayload) =>
      blogService.create(payload).then((r) => r.data.data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [KEY.blog] });
      toast.success("Article created");
    },
  });
}

export function useUpdateBlogPost() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({
      id,
      payload,
    }: {
      id: string;
      payload: UpdateBlogPostPayload;
    }) => blogService.update(id, payload).then((r) => r.data.data),
    onSuccess: (_data, vars) => {
      qc.invalidateQueries({ queryKey: [KEY.blog] });
      qc.invalidateQueries({ queryKey: QUERY_KEY.blog.versions(vars.id) });
      toast.success("Article updated");
    },
  });
}

// ── Write: workflow (Manager/Admin) ──
// No form → use onError to toast directly.

export function useGenerateBlogFromKb() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (kbId: string) =>
      blogService.generateFromKb(kbId).then((r) => r.data.data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [KEY.blog] });
      toast.success("AI blog generation requested");
    },
    onError: (error) => handleErrorApi({ error }),
  });
}

export function usePublishBlogPost() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) =>
      blogService.publish(id).then((r) => r.data.data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [KEY.blog] });
      toast.success("Published");
    },
    onError: (error) => handleErrorApi({ error }),
  });
}

export function useArchiveBlogPost() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) =>
      blogService.archive(id).then((r) => r.data.data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [KEY.blog] });
      toast.success("Archived");
    },
    onError: (error) => handleErrorApi({ error }),
  });
}

export function useDeleteBlogPost() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => blogService.remove(id).then((r) => r.data.data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [KEY.blog] });
      toast.success("Article deleted");
    },
    onError: (error) => handleErrorApi({ error }),
  });
}

/** BE blocks PUT (409) while the post is in this status → UI disables the Edit button. */
export function isBlogEditable(status?: BlogPostStatusEnum) {
  if (!status) return false;
  return (
    status !== BlogPostStatusEnum.Generating &&
    status !== BlogPostStatusEnum.Archived
  );
}

/**
 * How many blog posts sit in Draft — drives the sidebar badge on the Blog item.
 *
 * Manager/Admin only: those two roles decide what gets published, so the number is a
 * to-do for them. Staff would see a count they cannot act on, so the query is disabled
 * and the badge reads 0 — see AppLayout.
 *
 * PageSize 1 keeps the payload to one row; only `totalItems` is read. Counting the
 * loaded page instead would under-report as soon as there is more than one page.
 */
export function useBlogDraftCount() {
  const user = useSessionStore((s) => s.user);
  const canReview = checkRole(user, UserRole.MANAGER, UserRole.ADMIN);

  const { data } = useQuery({
    queryKey: QUERY_KEY.blog.list({
      status: BlogPostStatusEnum.Draft,
      countOnly: true,
    }),
    queryFn: () =>
      blogService
        .getList({ page: 1, pageSize: 1, status: BlogPostStatusEnum.Draft })
        .then((r) => r.data.data),
    enabled: canReview,
    staleTime: 60_000,
  });

  return canReview ? (data?.totalItems ?? 0) : 0;
}
