import axiosInstance from "@/shared/lib/axios";
import { ENDPOINTS } from "@/shared/utils/endpoints";
import type {
  CommonResponse,
  PaginationResponse,
} from "@/shared/types/api.types";
import type {
  NotificationGroupDto,
  NotificationGroupMemberDto,
  NotificationGroupListParams,
  NotificationGroupMemberListParams,
  CreateNotificationGroupPayload,
  UpdateNotificationGroupPayload,
  AddGroupMembersPayload,
  AddGroupMembersResult,
  BroadcastPayload,
  BroadcastPreviewPayload,
  BroadcastTemplatePreviewPayload,
  BroadcastChannelPreviewDto,
  BroadcastPreviewDto,
  BroadcastResultDto,
  NotificationBatchDto,
  NotificationBatchDetailDto,
  NotificationBatchListParams,
} from "@/features/admin/types/notification/notification-group.types";

export const notificationGroupService = {
  // System groups (by role) are listed first, then custom groups sorted by name.
  getList: (params?: NotificationGroupListParams) =>
    axiosInstance.get<CommonResponse<PaginationResponse<NotificationGroupDto>>>(
      ENDPOINTS.ADMIN.NOTIFICATION_GROUPS.LIST,
      { params },
    ),

  getById: (id: string) =>
    axiosInstance.get<CommonResponse<NotificationGroupDto>>(
      ENDPOINTS.ADMIN.NOTIFICATION_GROUPS.DETAIL(id),
    ),

  // Always creates a `Static` group. Role-based groups are generated by the seeder and cannot be created via API.
  // Duplicate name (case-insensitive) ⇒ 409.
  create: (payload: CreateNotificationGroupPayload) =>
    axiosInstance.post<CommonResponse<string>>(
      ENDPOINTS.ADMIN.NOTIFICATION_GROUPS.CREATE,
      payload,
    ),

  // Only changes name/description. System group ⇒ 409.
  update: (id: string, payload: UpdateNotificationGroupPayload) =>
    axiosInstance.put<CommonResponse<string>>(
      ENDPOINTS.ADMIN.NOTIFICATION_GROUPS.UPDATE(id),
      payload,
    ),

  // Soft-deletes the group + all members. Send history is NOT affected. System group ⇒ 409.
  remove: (id: string) =>
    axiosInstance.delete<CommonResponse<string>>(
      ENDPOINTS.ADMIN.NOTIFICATION_GROUPS.DELETE(id),
    ),

  getMembers: (id: string, params?: NotificationGroupMemberListParams) =>
    axiosInstance.get<
      CommonResponse<PaginationResponse<NotificationGroupMemberDto>>
    >(ENDPOINTS.ADMIN.NOTIFICATION_GROUPS.MEMBERS(id), { params }),

  // Skips ids that already exist / don't exist rather than failing the whole batch — see `AddGroupMembersResult`.
  addMembers: (id: string, payload: AddGroupMembersPayload) =>
    axiosInstance.post<CommonResponse<AddGroupMembersResult>>(
      ENDPOINTS.ADMIN.NOTIFICATION_GROUPS.ADD_MEMBERS(id),
      payload,
    ),

  removeMember: (id: string, userId: string) =>
    axiosInstance.delete<CommonResponse<string>>(
      ENDPOINTS.ADMIN.NOTIFICATION_GROUPS.REMOVE_MEMBER(id, userId),
    ),
};

export const notificationBroadcastService = {
  // Sends nothing — only returns the recipient count after deduplication. Shares the same logic
  // with `send` on the backend, so the two numbers can never diverge.
  preview: (payload: BroadcastPreviewPayload) =>
    axiosInstance.post<CommonResponse<BroadcastPreviewDto>>(
      ENDPOINTS.ADMIN.NOTIFICATION_BROADCAST.PREVIEW,
      payload,
    ),

  // Previews the CONTENT per channel when "use template" is enabled — different from `preview` above,
  // which only counts recipients. The backend builds the model using the same dispatcher shape, so the
  // text here matches exactly what gets sent for real.
  templatePreview: (payload: BroadcastTemplatePreviewPayload) =>
    axiosInstance.post<CommonResponse<BroadcastChannelPreviewDto[]>>(
      ENDPOINTS.ADMIN.NOTIFICATION_BROADCAST.TEMPLATE_PREVIEW,
      payload,
    ),

  // 400 with a specific reason when no valid recipients remain; does not create an orphaned send.
  send: (payload: BroadcastPayload) =>
    axiosInstance.post<CommonResponse<BroadcastResultDto>>(
      ENDPOINTS.ADMIN.NOTIFICATION_BROADCAST.SEND,
      payload,
    ),

  getBatches: (params?: NotificationBatchListParams) =>
    axiosInstance.get<CommonResponse<PaginationResponse<NotificationBatchDto>>>(
      ENDPOINTS.ADMIN.NOTIFICATION_BROADCAST.BATCHES,
      { params },
    ),

  getBatchById: (id: string) =>
    axiosInstance.get<CommonResponse<NotificationBatchDetailDto>>(
      ENDPOINTS.ADMIN.NOTIFICATION_BROADCAST.BATCH_DETAIL(id),
    ),
};
